// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';

export function AddSubscription(arg1:storage.SubscriptionInput):Promise<storage.SubscriptionRefreshResult>;

export function Connect(arg1:string,arg2:string):Promise<main.AppState>;

export function CreateServer(arg1:storage.ServerInput):Promise<storage.ServerRecord>;

export function CreateSubscription(arg1:storage.SubscriptionInput):Promise<storage.Subscription>;

export function DeleteServer(arg1:number):Promise<void>;

export function DeleteSubscription(arg1:number):Promise<void>;

export function Disconnect():Promise<main.AppState>;

export function GetServer(arg1:number):Promise<storage.ServerRecord>;

export function GetServers():Promise<Array<main.ServerSummary>>;

export function GetState():Promise<main.AppState>;

export function GetSubscription(arg1:number):Promise<storage.Subscription>;

export function ImportServers(arg1:string):Promise<storage.ImportResult>;

export function ListServers():Promise<Array<storage.ServerRecord>>;

export function ListSubscriptionServers(arg1:number):Promise<Array<storage.ServerRecord>>;

export function ListSubscriptions():Promise<Array<storage.Subscription>>;

export function PingServer(arg1:number):Promise<main.PingResult>;

export function RefreshSubscription(arg1:number):Promise<storage.SubscriptionRefreshResult>;

export function ReloadServers():Promise<main.AppState>;

export function SetServerSubscription(arg1:number,arg2:any):Promise<void>;

export function SpeedTestServer(arg1:number):Promise<main.PingResult>;

export function UpdateServer(arg1:number,arg2:storage.ServerInput):Promise<storage.ServerRecord>;

export function UpdateSubscription(arg1:number,arg2:storage.SubscriptionInput):Promise<storage.Subscription>;
