// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<main.AppState>;

export function Disconnect():Promise<main.AppState>;

export function GetState():Promise<main.AppState>;

export function ReloadServers():Promise<main.AppState>;
