// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1) {
  return window['go']['main']['App']['AddSubscription'](arg1);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function CreateSubscription(arg1) {
  return window['go']['main']['App']['CreateSubscription'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetSubscription(arg1) {
  return window['go']['main']['App']['GetSubscription'](arg1);
}

export function ImportServers(arg1) {
  return window['go']['main']['App']['ImportServers'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSubscriptionServers(arg1) {
  return window['go']['main']['App']['ListSubscriptionServers'](arg1);
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function RefreshSubscription(arg1) {
  return window['go']['main']['App']['RefreshSubscription'](arg1);
}

export function ReloadServers() {
  return window['go']['main']['App']['ReloadServers']();
}

export function SetServerSubscription(arg1, arg2) {
  return window['go']['main']['App']['SetServerSubscription'](arg1, arg2);
}

export function SpeedTestServer(arg1) {
  return window['go']['main']['App']['SpeedTestServer'](arg1);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2);
}

export function UpdateSubscription(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubscription'](arg1, arg2);
}
